package memory_test

import (
	"context"
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/nareg/goagent/memory"
)

func TestBuffer_StoreAndRecall(t *testing.T) {
	ctx := context.Background()

	tests := []struct {
		name        string
		stored      []string
		query       string
		topK        int
		wantLen     int
		wantTopContent string // expected content of the top result (substring)
	}{
		{
			name: "single match",
			stored: []string{
				"The capital of France is Paris",
				"Go is a statically typed language",
			},
			query:   "capital France",
			topK:    5,
			wantLen: 1,
			wantTopContent: "France",
		},
		{
			name: "multiple matches ranked by score",
			stored: []string{
				"The capital of France is Paris",
				"Paris has the Eiffel Tower",
				"Go is a statically typed language",
			},
			query:       "Paris France",
			topK:        5,
			wantLen:     2,
			wantTopContent: "France", // both words match → higher score
		},
		{
			name: "no match returns empty",
			stored: []string{
				"The capital of France is Paris",
				"Go is a statically typed language",
			},
			query:   "quantum physics",
			topK:    5,
			wantLen: 0,
		},
		{
			name: "topK limits results",
			stored: []string{
				"Go language is great",
				"Go language is fast",
				"Go language is simple",
				"Go language is fun",
			},
			query:   "go language",
			topK:    2,
			wantLen: 2,
		},
		{
			name: "topK zero returns all matches",
			stored: []string{
				"Go language is great",
				"Go language is fast",
				"Go language is simple",
			},
			query:   "go language",
			topK:    0,
			wantLen: 3,
		},
		{
			name: "case insensitive matching",
			stored: []string{"The CAPITAL of FRANCE is PARIS"},
			query:   "capital france paris",
			topK:    5,
			wantLen: 1,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			b := memory.NewBuffer(100)
			for _, content := range tc.stored {
				require.NoError(t, b.Store(ctx, memory.MemoryEntry{Content: content}))
			}

			results, err := b.Recall(ctx, tc.query, tc.topK)
			require.NoError(t, err)
			assert.Len(t, results, tc.wantLen)

			if tc.wantTopContent != "" && len(results) > 0 {
				assert.Contains(t, results[0].Content, tc.wantTopContent)
			}

			// Verify results are sorted descending by score.
			for i := 1; i < len(results); i++ {
				assert.GreaterOrEqual(t, results[i-1].Score, results[i].Score,
					"results should be sorted descending by score")
			}
		})
	}
}

func TestBuffer_CapacityEviction(t *testing.T) {
	ctx := context.Background()
	b := memory.NewBuffer(2)

	require.NoError(t, b.Store(ctx, memory.MemoryEntry{ID: "a", Content: "entry alpha xyzzy"}))
	require.NoError(t, b.Store(ctx, memory.MemoryEntry{ID: "b", Content: "entry bravo foobar"}))
	assert.Equal(t, 2, b.Len())

	// Adding a third evicts "a".
	require.NoError(t, b.Store(ctx, memory.MemoryEntry{ID: "c", Content: "entry charlie quux"}))
	assert.Equal(t, 2, b.Len())

	// "a" is gone.
	results, err := b.Recall(ctx, "xyzzy", 10)
	require.NoError(t, err)
	assert.Empty(t, results)

	// "c" is present.
	results, err = b.Recall(ctx, "quux", 10)
	require.NoError(t, err)
	assert.Len(t, results, 1)
	assert.Equal(t, "c", results[0].ID)
}

func TestBuffer_IDAutoGenerated(t *testing.T) {
	ctx := context.Background()
	b := memory.NewBuffer(10)

	require.NoError(t, b.Store(ctx, memory.MemoryEntry{Content: "auto id test entry"}))

	results, err := b.Recall(ctx, "auto id test", 1)
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.NotEmpty(t, results[0].ID, "ID should be auto-generated")
	assert.False(t, results[0].CreatedAt.IsZero(), "CreatedAt should be set")
}

func TestBuffer_ScoreIsZeroOnStore(t *testing.T) {
	ctx := context.Background()
	b := memory.NewBuffer(10)

	e := memory.MemoryEntry{Content: "test score zero", Score: 99.0}
	require.NoError(t, b.Store(ctx, e))

	results, err := b.Recall(ctx, "test score zero", 1)
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.NotEqual(t, 99.0, results[0].Score, "stored Score should be reset to 0 and re-computed on Recall")
}

func TestBuffer_UnlimitedCapacity(t *testing.T) {
	ctx := context.Background()
	b := memory.NewBuffer(0) // unlimited

	for i := 0; i < 50; i++ {
		require.NoError(t, b.Store(ctx, memory.MemoryEntry{
			Content: fmt.Sprintf("entry number %d with unique token tok%d", i, i),
		}))
	}
	assert.Equal(t, 50, b.Len())
}

func TestBuffer_TagsPreserved(t *testing.T) {
	ctx := context.Background()
	b := memory.NewBuffer(10)

	require.NoError(t, b.Store(ctx, memory.MemoryEntry{
		Content: "tagged entry about golang",
		Tags:    []string{"lang", "go"},
	}))

	results, err := b.Recall(ctx, "golang", 1)
	require.NoError(t, err)
	require.Len(t, results, 1)
	assert.Equal(t, []string{"lang", "go"}, results[0].Tags)
}
